### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Velken** [randomtdev/nexusmods_downloadfix#1]
Still having to wait for 5 second timer to countdown. Tampermonkey reports scrip is running.

**Comment by randomtdev** [comment]
What browser are you using? Are you on the latest version of the script? Are you getting any errors in console(Ctrl+Shift+I)?

**Comment by Velken** [comment]
Latest Google Chrome Built
Latest Script Version
Console gives this error:
![image](https://user-images.githubusercontent.com/8467292/70987342-72226600-209e-11ea-8a73-4982e26507e3.png)

**Comment by randomtdev** [comment]
This is an error unrelated to the script.
