### ISSUE TITLE
Sometimes downloads the file twice

### ISSUE THREAD

**Issue by Sabre142** [randomtdev/nexusmods_downloadfix#2]
For example, on Cathedral Assets Optimizer, when before downloading you get a popup about requirements for the mod, then click 'Download', you might get two files instead of one.

**Comment by randomtdev** [comment]
Are you clicking the Preparing download button and then clicking the Download button afterwards?
Clicking the download button while it's still preparing will make it automatically start once it's finished. So if you click it again afterwards it will re-download
