### ISSUE TITLE
Occaisionally doesn't work

### ISSUE THREAD

**Issue by Stifling-Bossness** [randomtdev/nexusmods_downloadfix#4]
Sometimes I still get redirected to the "buy or suffer" page, but not all the time. Just started a few hours ago, not sure if they added some randomness to the site or if it's on a timer.

**Comment by randomtdev** [comment]
When this happens, is it a regular manual download or a mod with a requirements popup? Also, does the download automatically start once reaching the nag page?

**Comment by Stifling-Bossness** [comment]
Manual download with a requirements pop-up. Does not automatically start, I have to hit the aptly-renamed "Boo You Suck" button to get it to start. I may be pressing the download button on the pop-up slightly before it finishes loading the pop-up, hard to tell on this crappy wifi.

**Comment by randomtdev** [comment]
So to clarify, this doesn't happen with regular downloads with no popups?

I was able to reproduce the issue and it just seems to be a problem with clicking the button before its been patched. I have an idea on how to fix this.

**Comment by Stifling-Bossness** [comment]
I don't seem to be able to reproduce it with independent files, no.

**Comment by randomtdev** [comment]
Well took some digging in the code and more google searching on how JS stuff works, but I've cleaned up the patching process for tabs & requirement windows. The button should now be patched before it even shows up.

Greasemonkey is no longer supported as of these changes though
