### ISSUE TITLE
Not working (for me)

### ISSUE THREAD

**Issue by sabinoplane** [randomtdev/nexusmods_downloadfix#5]
I'm using chrome with tampermonkey, got the script installed, tested downloading jcontainers and i still got the "choose download speed" page... maybe they've patched it again?

**Comment by randomtdev** [comment]
I just tested it on chrome with tampermonkey and it seems to work fine. Are you on the latest version? If so, send me a link to what mod you're trying to download, which file you're choosing, and if its a manual or mod manager download.

Send me a screenshot or copy/paste of your console (F12) before and after you click the download button.

**Comment by sabinoplane** [comment]
it's... possible i got the wrong version or something, i'm not very used to git hub so just to make sure
this is the download button right?
https://imgur.com/a/4dfCEve
in case it is the right downlod button and it's not my fault, i'll do what you just said
I'm using Skyrim SE, tested it in multiple mods like jcontainers and tk dodge (both of which i had to update) and i got the page in both of them. I'm also using mod manager download with vortex.
I'll send you the console screenshots in TK dodge
Before clicking: https://imgur.com/a/o9Xz396
After clicking: https://imgur.com/a/QwO4j1b
Also i just now realized something i probably should've mentioned but i didn't realize- I'm using an adblocker

**Comment by randomtdev** [comment]
Make sure the script is actually enabled and nothing is wrong with tampermonkey; From what I can tell the script isn't loading at all. If you can't find the issue, you can try Violentmonkey https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag

**Comment by sabinoplane** [comment]
it is enabled, i checked in the dashboard https://imgur.com/a/tEDhivb
also if you're wondering the other two scripts i have loaded do work...
i'll try violentmonkey tho
it worked fine with violentmonkey!
Thanks for doing this by the way, i promoted it again in the nexus reddit so as many people as possible find out about it. I won't give nexus a cent, but i'd gladly donate to you if you take donations!

**Comment by randomtdev** [comment]
No problem; Glad you got it working. Not sure why tampermonkey would have not loaded the script. And no, I don't take donations for this.

**Comment by nikzara** [comment]
FWIW, I also couldn't get this to work with Tampermonkey, and changing to Violentmonkey fixed it. 
¯\_(ツ)_/¯
