### ISSUE TITLE
top vortex button sends to download page

### ISSUE THREAD

**Issue by yarrmateys** [randomtdev/nexusmods_downloadfix#6]
while the buttons inside files section still work fine, the one on top of the page occasionally sends you to the nag page (seems to do it if a second click due to required dlc is present, this for example: https://www.nexusmods.com/fallout4/mods/32857), and boy are they salty about this script bypassing their forced nagware. the free download button is now called "boo you suck"

**Comment by randomtdev** [comment]
The "boo you suck" text was actually added by me when the script was just automatically downloading at first.

As for the issue, it does seem I completely forgot to add that functionality to those buttons in the most recent update; This is fixed now.
